hello:        Hello. Please authorize me to start working.
authorized:   Now I'll remember you. Say `help` to find out more about me.
stranger:     Sorry, but I don't know you. Try to add me into your roster.
help: |
  This is yatodo (Yet Another TODOs organizer).
  All TODOs have tags. Tags created automatically, when you add TODO to tag, like so:
    tag + todo
  Of course you can print your TODOs.
    tag :
  If tag is empty or equals '_', then all your TODOs are printed.
  Of course you can remove todo by its text
    tag - todo
  Did you notice numbers, when you printed TODOs? You can also delete TODOs by its number:
    tag - #5
  tag must be same tag you have used in printing TODOs.
nosuchtag:      No such tag
nosuchitem:     No such TODO
noteadded:      TODO added
noteexists:     TODO with this text already exists.
removednote:    TODO removed.
parserror:      You are doing it wrong.
nothing:        Nothing to display
multiple:       There is multiple TODOs to delete.
